### ISSUE TITLE
Wannier90.x can't be run with multiple cores

### ISSUE THREAD

**Issue by sAimen94** [conda-forge/qe-feedstock#42]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Dear all,

It seems for me that when running wannier90.x using more than one np the program stops. For example running:

`mpirun -np 6 wannier90.x -pp ce2o3`

```
At line 98 of file /home/conda/feedstock_root/build_artifacts/qe_1669353616205/work/external/wannier90/src/wannier_prog.F90 (unit = 10, file = 'ce2o3.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:
At line 98 of file /home/conda/feedstock_root/build_artifacts/qe_1669353616205/work/external/wannier90/src/wannier_prog.F90 (unit = 10, file = 'ce2o3.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:
At line 98 of file /home/conda/feedstock_root/build_artifacts/qe_1669353616205/work/external/wannier90/src/wannier_prog.F90 (unit = 10, file = 'ce2o3.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:
At line 98 of file /home/conda/feedstock_root/build_artifacts/qe_1669353616205/work/external/wannier90/src/wannier_prog.F90 (unit = 10, file = 'ce2o3.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:
At line 98 of file /home/conda/feedstock_root/build_artifacts/qe_1669353616205/work/external/wannier90/src/wannier_prog.F90 (unit = 10, file = 'ce2o3.werr')
Fortran runtime error: File cannot be deleted

Error termination. Backtrace:
#0  0x55fddbbabf40 in ???
#1  0x55fddbbab730 in ???
#0  0x55da85ce1f40 in ???
#1  0x55da85ce1730 in ???
#0  0x55cff2b3bf40 in ???
#1  0x55cff2b3b730 in ???
#0  0x559220c50f40 in ???
#1  0x559220c50730 in ???
#2  0x7f8a6ac29d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#3  0x7f8a6ac29e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#4  0x55fddbbab760 in ???
#2  0x7f7c53e29d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#3  0x7f7c53e29e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#4  0x55cff2b3b760 in ???
#2  0x7fd67e829d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#3  0x7fd67e829e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#4  0x559220c50760 in ???
#2  0x7f14e3c29d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#3  0x7f14e3c29e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#4  0x55da85ce1760 in ???
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
#0  0x55e720b8df40 in ???
#1  0x55e720b8d730 in ???
#2  0x7fd6cfa29d8f in __libc_start_call_main
	at ../sysdeps/nptl/libc_start_call_main.h:58
#3  0x7fd6cfa29e3f in __libc_start_main_impl
	at ../csu/libc-start.c:392
#4  0x55e720b8d760 in ???
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[56571,1],4]
  Exit code:    2
--------------------------------------------------------------------------

```

But running `mpirun -np 1 wannier90.x -pp ce2o3` works fine. 

The QE executable pw.x runs also fine in parallel. I've read in a similar issue (https://github.com/TRIQS/solid_dmft/discussions/29) that wannier90.x is not compiled by default with MPI support. 
Does this also apply for your conda package?

Thank you and best wishes,
Simon

### Installed packages

```shell
# packages in environment at /home/simon/miniconda3:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
anyio                     3.7.0              pyhd8ed1ab_1    conda-forge
argon2-cffi               21.3.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py39hb9d737c_2    conda-forge
asttokens                 2.2.1              pyhd8ed1ab_0    conda-forge
async-lru                 2.0.2              pyhd8ed1ab_0    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
babel                     2.12.1             pyhd8ed1ab_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
binutils_impl_linux-64    2.38                 h2a08ee3_1  
binutils_linux-64         2.38.0               hc2dff05_0  
bleach                    6.0.0              pyhd8ed1ab_0    conda-forge
boltons                   23.0.0           py39h06a4308_0  
boost-cpp                 1.78.0               h6582d0a_3    conda-forge
brotli                    1.0.9                h166bdaf_9    conda-forge
brotli-bin                1.0.9                h166bdaf_9    conda-forge
brotlipy                  0.7.0           py39h27cfd23_1003  
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.19.1               hd590300_0    conda-forge
ca-certificates           2023.5.7             hbcca054_0    conda-forge
certifi                   2023.5.7           pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py39h5eee18b_3  
charset-normalizer        2.0.4              pyhd3eb1b0_0  
conda                     23.5.0           py39hf3d152e_1    conda-forge
conda-content-trust       0.1.3            py39h06a4308_0  
conda-package-handling    2.0.2            py39h06a4308_0  
conda-package-streaming   0.7.0            py39h06a4308_0  
contourpy                 1.1.0            py39h7633fee_0    conda-forge
cryptography              39.0.1           py39h9ce1e76_0  
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
elpa                      2021.11.001     mpi_openmpi_haf9840c_3    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.1.1              pyhd8ed1ab_0    conda-forge
executing                 1.2.0              pyhd8ed1ab_0    conda-forge
fftw                      3.3.10          mpi_openmpi_h4a81ba8_8    conda-forge
flit-core                 3.9.0              pyhd8ed1ab_0    conda-forge
fonttools                 4.40.0           py39hd1e30aa_0    conda-forge
freetype                  2.12.1               hca18f0e_1    conda-forge
gcc_impl_linux-64         11.2.0               h1234567_1  
gcc_linux-64              11.2.0               h5c386dc_0  
gmp                       6.2.1                h58526e2_0    conda-forge
gxx_impl_linux-64         11.2.0               h1234567_1  
gxx_linux-64              11.2.0               hc2dff05_0  
hdf5                      1.12.2          mpi_openmpi_hb3f3608_1    conda-forge
icu                       72.1                 hcb278e6_0    conda-forge
idna                      3.4              py39h06a4308_0  
importlib-metadata        6.7.0              pyha770c72_0    conda-forge
importlib-resources       5.12.0             pyhd8ed1ab_0    conda-forge
importlib_metadata        6.7.0                hd8ed1ab_0    conda-forge
importlib_resources       5.12.0             pyhd8ed1ab_0    conda-forge
ipykernel                 5.5.5            py39hef51801_0    conda-forge
ipython                   8.14.0             pyh41d4057_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.18.2             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonpatch                 1.32               pyhd3eb1b0_0  
jsonpointer               2.1                pyhd3eb1b0_0  
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter-lsp               2.2.0              pyhd8ed1ab_0    conda-forge
jupyter_client            8.3.0              pyhd8ed1ab_0    conda-forge
jupyter_core              5.3.1            py39hf3d152e_0    conda-forge
jupyter_events            0.6.3              pyhd8ed1ab_0    conda-forge
jupyter_server            2.7.0              pyhd8ed1ab_0    conda-forge
jupyter_server_terminals  0.4.4              pyhd8ed1ab_1    conda-forge
jupyterlab                4.0.2              pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.2.2              pyhd8ed1ab_0    conda-forge
jupyterlab_server         2.23.0             pyhd8ed1ab_0    conda-forge
kernel-headers_linux-64   2.6.32              he073ed8_15    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
kiwisolver                1.4.4            py39hf939315_1    conda-forge
krb5                      1.20.1               hf9c8cef_0    conda-forge
lcms2                     2.15                 haa2dc70_1    conda-forge
ld_impl_linux-64          2.38                 h1181459_1  
lerc                      4.0.0                h27087fc_0    conda-forge
libaec                    1.0.6                hcb278e6_1    conda-forge
libblas                   3.9.0           17_linux64_openblas    conda-forge
libbrotlicommon           1.0.9                h166bdaf_9    conda-forge
libbrotlidec              1.0.9                h166bdaf_9    conda-forge
libbrotlienc              1.0.9                h166bdaf_9    conda-forge
libcblas                  3.9.0           17_linux64_openblas    conda-forge
libclang                  16.0.6          default_h1cdf331_0    conda-forge
libclang13                16.0.6          default_h4d60ac6_0    conda-forge
libcurl                   8.1.1                h91b91d3_1  
libdeflate                1.18                 h0b41bf4_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h6a678d5_6  
libgcc-devel_linux-64     11.2.0               h1234567_1  
libgcc-ng                 13.1.0               he5830b7_0    conda-forge
libgfortran-ng            13.1.0               h69a702a_0    conda-forge
libgfortran5              13.1.0               h15d22d2_0    conda-forge
libgomp                   13.1.0               he5830b7_0    conda-forge
libiconv                  1.17                 h166bdaf_0    conda-forge
libjpeg-turbo             2.1.5.1              h0b41bf4_0    conda-forge
liblapack                 3.9.0           17_linux64_openblas    conda-forge
liblapacke                3.9.0           17_linux64_openblas    conda-forge
libllvm16                 16.0.6               h5cf9203_0    conda-forge
libnghttp2                1.52.0               ha637b67_1  
libopenblas               0.3.23          pthreads_h80387f5_0    conda-forge
libpng                    1.6.39               h753d276_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               h37d81fd_2  
libstdcxx-devel_linux-64  11.2.0               h1234567_1  
libstdcxx-ng              13.1.0               hfd8a6a1_0    conda-forge
libtiff                   4.5.1                h8b53f26_0    conda-forge
libwebp-base              1.3.1                hd590300_0    conda-forge
libxcb                    1.15                 h0b41bf4_0    conda-forge
libxml2                   2.11.4               h0d562d8_0    conda-forge
libzlib                   1.2.13               hd590300_5    conda-forge
mako                      1.2.4              pyhd8ed1ab_0    conda-forge
markupsafe                2.1.1            py39h7f8727e_0  
matplotlib-base           3.7.1            py39he190548_0    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.0              pyhd8ed1ab_0    conda-forge
mpi                       1.0                     openmpi    conda-forge
mpi4py                    3.1.4            py39h5418507_0    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclient                  0.8.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.6.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.9.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  h6a678d5_0  
nfft                      3.5.2                h1873fe1_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numpy                     1.25.0           py39h6183b62_0    conda-forge
openjpeg                  2.5.0                hfec8fc6_2    conda-forge
openmpi                   4.1.5              h414af15_101    conda-forge
openssl                   1.1.1u               hd590300_0    conda-forge
overrides                 7.3.1              pyhd8ed1ab_0    conda-forge
packaging                 23.0             py39h06a4308_0  
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.5.0            py39haaeba84_1    conda-forge
pip                       23.0.1           py39h06a4308_0  
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_0    conda-forge
platformdirs              3.8.0              pyhd8ed1ab_0    conda-forge
pluggy                    1.0.0            py39h06a4308_1  
pooch                     1.7.0              pyha770c72_3    conda-forge
prometheus_client         0.17.0             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.38             pyha770c72_0    conda-forge
prompt_toolkit            3.0.38               hd8ed1ab_0    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
pure_eval                 0.2.2              pyhd8ed1ab_0    conda-forge
pycosat                   0.6.4            py39h5eee18b_0  
pycparser                 2.21               pyhd3eb1b0_0  
pygments                  2.15.1             pyhd8ed1ab_0    conda-forge
pyopenssl                 23.0.0           py39h06a4308_0  
pyparsing                 3.1.0              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.0           py39heee7806_0  
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.16               h7a1cb2a_2  
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.17.1             pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.7              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pytz                      2023.3             pyhd8ed1ab_0    conda-forge
pyyaml                    6.0              py39hb9d737c_4    conda-forge
pyzmq                     25.1.0           py39h6a678d5_0  
qe                        7.1                  h262a2fe_1    conda-forge
readline                  8.2                  h5eee18b_0  
requests                  2.28.1           py39h06a4308_1  
rfc3339-validator         0.1.4              pyhd8ed1ab_0    conda-forge
rfc3986-validator         0.1.1              pyh9f0ad1d_0    conda-forge
ruamel.yaml               0.17.21          py39h5eee18b_0  
ruamel.yaml.clib          0.2.6            py39h5eee18b_1  
scalapack                 2.2.0                h67de57e_1    conda-forge
scipy                     1.11.1           py39h6183b62_0    conda-forge
send2trash                1.8.2              pyh41d4057_0    conda-forge
setuptools                65.6.3           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.41.1               h5eee18b_0  
stack_data                0.6.2              pyhd8ed1ab_0    conda-forge
sysroot_linux-64          2.12                he073ed8_15    conda-forge
terminado                 0.17.1             pyh41d4057_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h1ccaba5_0  
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toolz                     0.12.0           py39h06a4308_0  
tornado                   6.2              py39h5eee18b_0  
tqdm                      4.65.0           py39hb070fc8_0  
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
triqs                     3.1.1            py39h254ea2c_4    conda-forge
triqs_cthyb               3.1.1            py39h1c15670_1    conda-forge
triqs_dft_tools           3.1.0            py39h39ac338_1    conda-forge
typing-extensions         4.7.0                hd8ed1ab_0    conda-forge
typing_extensions         4.7.0              pyha770c72_0    conda-forge
typing_utils              0.1.0              pyhd8ed1ab_0    conda-forge
tzdata                    2023c                h04d1e81_0  
unicodedata2              15.0.0           py39hb9d737c_0    conda-forge
urllib3                   1.26.15          py39h06a4308_0  
wcwidth                   0.2.6              pyhd8ed1ab_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
wheel                     0.38.4           py39h06a4308_0  
xorg-libxau               1.0.11               hd590300_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xz                        5.2.10               h5eee18b_1  
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hd590300_5    conda-forge
zstandard                 0.19.0           py39h5eee18b_0  
zstd                      1.5.2                h3eb15da_6    conda-forge
```

### Environment info

```shell
active environment : base
    active env location : /home/simon/miniconda3
            shell level : 1
       user config file : /home/simon/.condarc
 populated config files : 
          conda version : 23.5.0
    conda-build version : not installed
         python version : 3.9.16.final.0
       virtual packages : __archspec=1=x86_64
                          __glibc=2.35=0
                          __linux=5.19.0=0
                          __unix=0=0
       base environment : /home/simon/miniconda3  (writable)
      conda av data dir : /home/simon/miniconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/simon/miniconda3/pkgs
                          /home/simon/.conda/pkgs
       envs directories : /home/simon/miniconda3/envs
                          /home/simon/.conda/envs
               platform : linux-64
             user-agent : conda/23.5.0 requests/2.28.1 CPython/3.9.16 Linux/5.19.0-46-generic ubuntu/22.04.2 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by ltalirz** [comment]
@giovannipizzi could you comment on what might be the issue here?

**Comment by ltalirz** [comment]
This is Wannier90 bundled with QE.

QE build script: https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc

**Comment by sAimen94** [comment]
The guess is correct, it runs in serial mode.

**Comment by giovannipizzi** [comment]
Hi, I'm not sure the build system of w90 as included in qe is fully updated. Indeed the best is to have a different conda recipe for w90 alone? Building it as part of qe is just for convenience, but the w90 code is fully independent from qe, so I think it makes more sense to have it independent (eg, if a siesta user wants to use w90, he shouldn't need to install qe)
